repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^doc/.*
      - id: trailing-whitespace
        exclude: ^doc/.*
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.4
    hooks:
      - id: maven-compile
        types_or: [ java, xml ]
      - id: maven-spotless-apply
        types_or: [ java, xml ]